#!/bin/bash

if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ] || [ ! -z "$4" ]; then 
    echo "between requires exactly three arguments"
    exit 255
fi

stdout0=`cat`
stdout1=$(echo -n "$stdout0" | eval "$1") && stdout2=$(echo -n "$stdout1" | eval "$3") && stdout3=$(echo -n "$stdout2" | eval "$2") && { 
    #echo "stdout1=[$stdout1]" >&2
    #echo "stdout2=[$stdout2]" >&2
    #echo "stdout3=[$stdout3]" >&2
    echo -n "$stdout3"; exit 0; }

exit 1

