#!/bin/bash

if [ -z "$1" ] || [ ! -z "$2" ]; then 
    echo "match requires exactly one argument"
    exit 255
fi

IFS=
read -rn "${#1}" in

#echo "in=[$in]" >&2
#echo "stdout=[$stdout]" >&2

if [ "$1" = "$in" ]; then
    echo -n "$in" 1>&2
    cat
    exit 0
fi
exit 1
