#!/bin/bash

stdin=`cat`

echo -n "rmSpaces... "
pass1=$(rmSpaces <<< "$1" 2>&1)
echo "done."
echo -n "parensToQuote... "
pass2=$(parenToQuotes 1 <<< "$pass1" 2>&1)
echo "done."

echo "pass2=[$pass2]"
eval "msed \"$pass2\"" <<< "$stdin"

#language="rmSpaces"
#
##parsed=$(parsec "$language" <<< "$1" 2>&1 > /dev/null)
#parsed=$(parsec rmSpaces <<< "$1" 2>&1 > /dev/null)
#ret=$?
#
#echo "parsed=[$parsed]"
#echo "stderr=[$stderr]" 
#echo
#echo "$ret"
#
#exit $ret
