#!/bin/bash

IFS=
read -n 1 next

if [ ! -z "$1" ]; then
    depth="$1"
else
    depth=0
fi

function escapeQuotes
{
    #echo "\$1=$1" 1>&2
    #echo
    if [ "$1" -eq 0 ]; then
        echo -n "\"" 
    else 
        local newdepth=$(($1 - 1))
        local res=$(escapeQuotes $newdepth)
        #echo "sizeof(res)=${#res}"
        #echo "res=[$res]"
        for ((i=0; i<${#res}; i++ )); do
            if [ "${res:$i:1}" = '"' ]; then
                echo -n "\\\"" 
            elif [ "${res:$i:1}" = '\' ]; then
                echo -n "\\\\"
            fi
        done
        #echo -n "\\$res" 1>&2
    fi
}

if [ "$next" = "(" ]; then
    res=$(escapeQuotes "$depth" "\"")
    echo -n "$res" 1>&2
    depth=$(($depth+1))
    parenToQuotes "$depth"

elif [ "$next" = ")" ]; then
    ((depth=$depth-1))
    res=$(escapeQuotes "$depth" "\"")
    echo -n "$res" 1>&2
    parenToQuotes "$depth"

elif [ -z "$next" ]; then
    exit 0

else
    echo -n "$next" 1>&2
    parenToQuotes "$depth"
fi

