#!/bin/bash

if [ -z "$1" ] || [ ! -z "$2" ]; then 
    echo "parsec requires exactly one argument"
    exit 255
fi

#tmpdir=`mktemp`
tmpdir="/tmp"
#tmpdir="./"
eval "$1" > $tmpdir/stdout 2> "$tmpdir/stderr"
#exec 3>&1
#stderr=$(eval "$1" 2>&1 >&3)
#stdout=$({ stderr=$(eval "$1" 2>&1 1>&3-) ;} 3>&1)
#stdout=$({ stderr=$(eval "$1" 2>&1 1>&3-) ;} 3>&1)
#stdout=$(cat <&3)
ret=$?

echo "$stderr" >&2
echo "stderr=[$(cat $tmpdir/stderr)]" 
echo "stdout=[$(cat $tmpdir/stdout)]" 
echo
echo "exit=$ret"

exit $ret
