#!/bin/bash

if [ -z "$1" ] || [ ! -z "$2" ]; then 
    echo "many requires exactly one argument"
    exit 255
fi

stdin=`cat`

if [ ! -z "$stdin" ] && stdout=`eval "$1" <<< "$stdin"`; then
    #echo "stdout=[$stdout]" >&2
    "$0" "$1" <<< "$stdout"
else
    #echo "else" >&2
    cat <<< "$stdin"
fi
